/* CVS $Id: $ */
package br.unifor.mia.serin.server;

import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;

/**
 * Vocabulary definitions from owl/serin.owl
 * 
 * @author Auto-generated by schemagen on 23 Ago 2012 10:17
 */
public class Serin {
	/**
	 * <p>
	 * The ontology model that holds the vocabulary terms
	 * </p>
	 */
	private static OntModel m_model = ModelFactory.createOntologyModel(
			OntModelSpec.OWL_MEM, null);

	/**
	 * <p>
	 * The namespace of the vocabulary as a string
	 * </p>
	 */
	public static final String NS = "http://www.unifor.br/serin.owl#";

	/**
	 * <p>
	 * The namespace of the vocabulary as a string
	 * </p>
	 * 
	 * @see #NS
	 */
	public static String getURI() {
		return NS;
	}

	/**
	 * <p>
	 * The namespace of the vocabulary as a resource
	 * </p>
	 */
	public static final Resource NAMESPACE = m_model.createResource(NS);

	public static final AnnotationProperty DELETE = m_model
			.createAnnotationProperty("http://www.unifor.br/serin.owl#delete");

	public static final AnnotationProperty GET = m_model
			.createAnnotationProperty("http://www.unifor.br/serin.owl#get");

	public static final AnnotationProperty LIST = m_model
			.createAnnotationProperty("http://www.unifor.br/serin.owl#list");

	public static final AnnotationProperty POST = m_model
			.createAnnotationProperty("http://www.unifor.br/serin.owl#post");

	public static final AnnotationProperty PUT = m_model
			.createAnnotationProperty("http://www.unifor.br/serin.owl#put");

}
