/* CVS $Id: $ */
package br.unifor.mia.serin.server;

import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;

/**
 * Vocabulary definitions from owl/veiculo.owl
 * 
 * @author Auto-generated by schemagen on 23 Ago 2012 10:14
 */
public class Veiculo {
	/**
	 * <p>
	 * The ontology model that holds the vocabulary terms
	 * </p>
	 */
	protected static OntModel m_model = ModelFactory.createOntologyModel(
			OntModelSpec.OWL_MEM, null);

	/**
	 * <p>
	 * The namespace of the vocabulary as a string
	 * </p>
	 */
	public static final String NS = "http://www.unifor.br/veiculo.owl#";

	/**
	 * <p>
	 * The namespace of the vocabulary as a string
	 * </p>
	 * 
	 * @see #NS
	 */
	public static String getURI() {
		return NS;
	}

	/**
	 * <p>
	 * The namespace of the vocabulary as a resource
	 * </p>
	 */
	public static final Resource NAMESPACE = m_model.createResource(NS);

	public static final DatatypeProperty MARCA = m_model
			.createDatatypeProperty("http://www.unifor.br/veiculo.owl#marca");

	public static final DatatypeProperty MODELO = m_model
			.createDatatypeProperty("http://www.unifor.br/veiculo.owl#modelo");

	public static final OntClass VEICULO = m_model
			.createClass("http://www.unifor.br/veiculo.owl#Veiculo");

}
