/* CVS $Id: $ */

import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;

/**
 * Vocabulary definitions from owl/clinic.owl
 *
 * @author Auto-generated by schemagen on 23 Ago 2012 10:14
 */
public class Clinic {
    /**
     * <p>
     * The ontology model that holds the vocabulary terms
     * </p>
     */
    private static OntModel m_model = ModelFactory.createOntologyModel();

    /**
     * <p>
     * The namespace of the vocabulary as a string
     * </p>
     */
    public static final String NS = "http://www.unifor.br/clinic.owl#";

    /**
     * <p>
     * The namespace of the vocabulary as a string
     * </p>
     *
     * @see #NS
     */
    public static String getURI() {
        return NS;
    }

    /**
     * <p>
     * The namespace of the vocabulary as a resource
     * </p>
     */
    public static final Resource NAMESPACE = m_model.createResource(NS);

    public static final ObjectProperty attendedBy = m_model
            .createObjectProperty(NS + "attendedBy", true);

    public static final ObjectProperty isSpecializedIn = m_model
            .createObjectProperty(NS + "isSpecializedIn", true);

    public static final DatatypeProperty PHONENUMBER = m_model
            .createDatatypeProperty(NS + "phoneNumber", true);

    public static final DatatypeProperty DOCTORNAME = m_model
            .createDatatypeProperty(NS + "doctorName", true);

    public static final DatatypeProperty CLINICNAME = m_model
            .createDatatypeProperty(NS + "clinicName", true);

    public static final DatatypeProperty DESCRIPTION = m_model
            .createDatatypeProperty(NS + "description", true);

    public static final DatatypeProperty ADDRESS = m_model
            .createDatatypeProperty(NS + "address", true);

    public static final OntClass CLINIC = m_model.createClass(NS + "Clinic");

    public static final OntClass DOCTOR = m_model.createClass(NS + "Doctor");

    public static final OntClass SPECIALTY = m_model.createClass(NS
            + "Specialty");
}