/* CVS $Id: $ */
package br.unifor.mia.serin.server.vehicle;

import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;

/**
 * Vocabulary definitions from owl/vehicle.owl
 * 
 * @author Auto-generated by schemagen on 23 Ago 2012 10:14
 */
public class Vehicle {
	/**
	 * <p>
	 * The ontology model that holds the vocabulary terms
	 * </p>
	 */
	private static OntModel m_model = ModelFactory.createOntologyModel(OntModelSpec.OWL_MEM, null);

	/**
	 * <p>
	 * The namespace of the vocabulary as a string
	 * </p>
	 */
	public static final String NS = "http://www.unifor.br/vehicle.owl#";

	/**
	 * <p>
	 * The namespace of the vocabulary as a string
	 * </p>
	 * 
	 * @see #NS
	 */
	public static String getURI() {
		return NS;
	}

	/**
	 * <p>
	 * The namespace of the vocabulary as a resource
	 * </p>
	 */
	public static final Resource NAMESPACE = m_model.createResource(NS);

	public static final DatatypeProperty BRAND = m_model.createDatatypeProperty("http://www.unifor.br/vehicle.owl#brand");

	public static final DatatypeProperty MODEL = m_model.createDatatypeProperty("http://www.unifor.br/vehicle.owl#model");

	public static final OntClass VEHICLE = m_model.createClass("http://www.unifor.br/vehicle.owl#Vehicle");
}
